version: '3.7'
services:
  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  puppeteer:
    image: node:16.3.0-alpine
    tty: true
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
