version: '3.7'
services:
  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  node:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - 5555:5555

  rabbitmq:
    image: rabbitmq:3.8.16-alpine
    ports:
      - 5672:5672
